Nytt program-option på eventer
bekk/bekk-arrangement-svc pull request #108
Opened 2022-10-12 08:02 UTC by kcs85

Ønske fra design om å kunne legge inn og vise et program med hvit bakgrunn, til høyre for beskrivelsen. 

- Har lagt inn et nytt optional felt i event-tabellen ("program") 
- Valg under editmode for å legge til program
- Visning av program med hvit bakgrunn etter opprettelse
- Lagt til beskrivelse for pseudomarkdown for bold og italics

![image](https://user-images.githubusercontent.com/36476370/195284663-20d74ca7-cb53-4cc0-b476-5c281c29d027.png)
![image](https://user-images.githubusercontent.com/36476370/195285134-582b69ae-fa62-4611-a23b-ed4a67f83281.png)
![image](https://user-images.githubusercontent.com/36476370/195284417-eb0d792d-7bf1-4859-8bc8-6fb695b33519.png)

2022-10-12 08:03 UTC, kcs85 commented on Frontend/package.json
>      "build": "react-scripts build",
så det også funker på windows

2022-10-13 06:51 UTC, Bjorn-Strom requested changes
Kodemessig ser dette veldig bra ut, bra jobba 👍 

Siden du har lagt `program` til events må dette også legges til `Generator.fs` under tests, testene er brukket.

Jeg synes kanskje frontenden kan tweakes litt på.

Formateringshjelp er mellom de to feltene som støtter pseudo-markdown. Det føles litt rart ut.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/8441485/195522085-ed1a2377-e2a8-4438-b1a9-973da03d7883.png">

Når man ser på et event har vi veldig mye ubrukt space til høyre, mens programmet ligger skikkelig skviset inn sammen med beskrivelsen.
<img width="2" alt="image" src="https://user-images.githubusercontent.com/8441485/195522588-6b7244f3-8a9f-46d1-8652-369945fc1863.png">

Synes det ser bra ut på mobil 👍 

Veldig bra jobba! Men vi må fikse testene og jeg synes det er en liten vei å gå på det visuelle.

2022-10-13 06:51 UTC, Bjorn-Strom commented on Frontend/src/components/EditEvent/EditEvent/EditEvent.tsx
> +  program: 'Legg inn program for eventen. Vi støtter litt pseudomarkdown.'
Dette er samme markdown som i beskrivelse, sant?
Kan det være greit å forklare det her?

2022-10-13 07:08 UTC, simendsjo commented on Frontend/package.json
>      "build": "react-scripts build",
Dette er ting som håndteres av shellet. Hvilket shell er det du prøver som ikke støtter denne syntaksen? Har ikke Windows lett tilgjengelig, men mener å huske jeg har pleid å bare gjøre det på samme måte som for bash og andre shell.

2022-10-13 07:53 UTC, kcs85 commented on Frontend/package.json
>      "build": "react-scripts build",
windows powershell i dette tilfellet

2022-10-13 07:56 UTC, kcs85 commented on Frontend/src/components/EditEvent/EditEvent/EditEvent.tsx
> +  program: 'Legg inn program for eventen. Vi støtter litt pseudomarkdown.'
Ja, samme markdown. Er det nok å forklare at det er samme markdown som for beskrivelsen? eller bør vi også legge til den blå Formateringshjelpen under program også?

2022-10-13 10:02 UTC, simendsjo commented on Frontend/package.json
>      "build": "react-scripts build",
Testet powershell på Linux, og fikk samme der ja. Jeg bruker primært bash på Windows også.

2022-10-13 12:41 UTC, ingridlarssen commented on Frontend/src/components/ViewEvent/ViewEvent.module.scss
> +.program {
Litt usikker på om denne kommentaren legges på riktig sted nå, men er det mulig å gjøre programmet litt bredere på mobilvisning? 

<img width="426" alt="bilde" src="https://user-images.githubusercontent.com/22234149/195597756-9820f507-c749-40c2-af3e-ca5e04d7002e.png">

2022-10-14 07:42 UTC, kcs85 commented on Frontend/src/components/ViewEvent/ViewEvent.module.scss
> +.program {
Har satt width til fit-content så vil endres basert på størrelsen. Men, kan godt også sette en min-bredde om ønskelig? 
Med mer tekst ser det slik ut:
![image](https://user-images.githubusercontent.com/36476370/195790489-865fd514-49b1-414c-8a05-918b292aafcd.png)

2022-10-14 08:30 UTC, kcs85 commented on Frontend/src/components/ViewEvent/ViewEvent.module.scss
> +.program {
Endre til maksbredde på mobil nå

2022-10-14 08:57 UTC, ingridlarssen commented on Frontend/src/components/ViewEvent/ViewEvent.module.scss
> +.program {
Ser at den da blir veldig bred på noen skjermstørrelser igjen
![bilde](https://user-images.githubusercontent.com/22234149/195804446-885f1cfa-8c64-4617-9f0e-f4a708d819b3.png)

Hva hvis width: fit-content flyttes tilbake der den var, også legger på en min-width på rundt 250px? Altså noe sånt?:
![bilde](https://user-images.githubusercontent.com/22234149/195806590-3624be2c-b0b9-4eab-bd0c-b4ad0d8d8c66.png)

Hva tenker du om det?

2022-10-14 10:12 UTC, kcs85 commented on Frontend/src/components/ViewEvent/ViewEvent.module.scss
> +.program {
oki, kan godt det

2022-10-14 10:43 UTC, merged