Feature/better increase capacity checks
bekk/bekk-arrangement-svc pull request #34
Opened 2021-06-25 14:51 UTC by tskj

Har prøvd å ta høyde for at man skal kunne utvide et arrangement. Det er mange caser å tenke på; man kan alltid utvide et arrangement slik at alle får plass, man kan utvide et arrangement som har venteliste, og man kan ikkje utvide et arrangement som hadde venteliste men kor man fjerner ventelista.  Osv.

Håper koden er forståelig. Har testa en del og funne eit par bugs som er fiksa, men sikkert fleire caser eg har missa.

Denne tar ikkje høgde for at det må sendes epost til dei som eventuelt får plass på ventelista! Så dette er en WIP. Er veldig nysgjerrig på ideer til korleis det er smooth i koden å finne ut kven som har fått plass, og så sende mail.

2021-06-28 11:24 UTC, TheodorRene requested changes
For å finne ut hvem du skal sende epost til er vel det beste å hente ut ventelista, få differanse X på endring MaxParticipants og sende epost til topp  X participants. Det burde kanskje være en del av denne PRen siden det er ganske viktig feature

2021-06-28 11:24 UTC, TheodorRene commented on src/Events/Validation.fs
> +    let assertCapacity (oldEvent: Event) (newEvent: Event) =
``` assertValidCapacityChange ``` er kanskje et tydeligere navn?

2021-06-28 11:24 UTC, TheodorRene commented on src/Events/Validation.fs
> +
Veldig nice at du tar disse casene i hver sin If-setning, selvom de kunne vært kun en.

2021-06-28 11:24 UTC, TheodorRene commented on src/Events/Validation.fs
> +            if newMax >= oldMax && oldMax <> 0 && newEvent.HasWaitingList then
Jeg forstår ikke helt. Hvis man "beholder størrelsen" så betyr det jo at man ikke gjør noen endring, og dermed trenger man ikke å validere? Man trenger ikke ha venteliste for å få lov til å beholde samme antall plasser. 
Altså:
``` 
       // Ingen endring
       if newMax = oldMax then return ()
```
 er ikke dekket så vidt jeg ser

2021-06-28 11:25 UTC, TheodorRene commented on src/Events/Validation.fs
> +    let assertCapacity (oldEvent: Event) (newEvent: Event) =
``` assertValidMaxCapacityChange ```

Mange muligheter, vet ikke hvem jeg liker best

2021-06-28 12:58 UTC, sarahjelle commented on src/Events/Validation.fs
> +    let assertCapacity (oldEvent: Event) (newEvent: Event) =
Synes assertMaxCapasityChange fordi det viser tydelig at det er max hva man kan endre til

2021-06-29 06:20 UTC, sarahjelle commented on src/Events/Validation.fs
> +            if newMax >= oldMax && oldMax <> 0 && newEvent.HasWaitingList then
Hvorfor trenger man å sjekke den øverste med venteliste? Er det for å sikre at man ikke tar vekk ventelista om det eksisterte en fra før?

2021-06-29 06:25 UTC, sarahjelle commented on src/Events/Service.fs
> +        -- Summer intern 2021
Liker signaturen

2021-06-29 06:30 UTC, sarahjelle approved these changes
Syns dette ser bra ut og støtter forslaget til Theodor om å sende ut mail til de deltakerne som får plass fra ventelisten. Eller så kan kanskje gjøres på lignende måte som det gjøres når folk rykker opp fra venteliste nå (mulig de to måtene er like)

2021-06-30 13:11 UTC, TheodorRene commented on src/Events/Service.fs
> +        -- Summer intern 2021
takk

2021-07-02 12:09 UTC, tskj commented on src/Events/Validation.fs
> +    let assertCapacity (oldEvent: Event) (newEvent: Event) =
Den sjekker også venteliste, så ikkje bare maxParticipants som testes 🤔

2021-07-02 12:10 UTC, tskj commented on src/Events/Validation.fs
> +            if newMax >= oldMax && oldMax <> 0 && newEvent.HasWaitingList then
Husker ikkje koden nå sjølvsagt 😅 men trur du har rett @sarahjelle , det er nok for å passe på at man ikkje fjerner ventelista om det er folk på den!

2021-07-02 12:13 UTC, TheodorRene commented on src/Events/Validation.fs
> +    let assertCapacity (oldEvent: Event) (newEvent: Event) =
assertCapacityChange da? For å fortelle at den validerer en differanse? ikke bare en verdi

2021-07-05 12:09 UTC, TheodorRene commented on src/Events/Service.fs
> +            yield sendMailToPeopleWhoHaveReceivedASpotDueToIncreasedCapacity oldEvent newEvent
Rekkefølgen blir feil her.

2021-07-05 12:40 UTC, merged