Add EmployeeId to participant and event if possible
bekk/bekk-arrangement-svc pull request #40
Opened 2021-07-09 13:00 UTC by TheodorRene

2021-07-09 13:00 UTC, TheodorRene commented on src/Common/Auth.fs
> +    let employeeIdClaim = "https://api.bekk.no/claims/employeeId"
Denne burde kanskje lagres et annet sted?

2021-07-09 13:00 UTC, TheodorRene commented on src/Events/Queries.fs
> +            let! event = Models.writeToDomain (Guid.NewGuid()) event (Guid.NewGuid()) false employeeId |> ignoreContext
Denne begynner å bli kaos

2021-07-09 13:01 UTC, TheodorRene commented on src/Events/UserMessages.fs
> +        $"Kunne ikke hente ut bruker id" |> InternalErrorMessage
særskrivingsfeil?

2021-07-09 13:02 UTC, TheodorRene commented
Legg merke til at Event.EmployeeID er forskjellige fra Participant.EmployeeID

2021-07-12 08:34 UTC, tskj commented on src/Common/Auth.fs
> +    let employeeIdClaim = "https://api.bekk.no/claims/employeeId"
Ja

2021-07-12 08:35 UTC, tskj commented on src/Events/Queries.fs
> +            let! event = Models.writeToDomain (Guid.NewGuid()) event (Guid.NewGuid()) false employeeId |> ignoreContext
Synes EventReduced er en god ide, men kanskje vi kan lage et kor på det og ta det seinare.

2021-07-12 08:36 UTC, tskj commented
> Legg merke til at Event.EmployeeID er forskjellige fra Participant.EmployeeID

Kva meiner du med dette? 🤔

2021-07-12 08:42 UTC, tskj approved these changes
Dette var fint! 😄

2021-07-12 08:42 UTC, tskj commented on src/Events/Handlers.fs
> +                            >> Option.withError [UserMessages.couldNotRetrieveUserId] // Result<EmployeeId, UserMessage list>
Vent har du lagt inn desse kommentarane som IDEen bruker å vise? 🤔😂

2021-07-12 08:42 UTC, tskj commented on src/Events/Handlers.fs
> +            let! updatedEvent = Service.updateEvent employeeId (Id id) writeModel
Det som er litt interessant her ref `ReducedEventModel` ellerno er jo at man kan redigere andre sine arrangementer (dersom man har edit-token), og da vil organizerId bli oppdatert? 🤔 Usikker på om det er bug eller feature.

2021-07-12 08:42 UTC, tskj commented on src/Participants/Models.fs
> +           }
Denne bracen er indentert litt rart.

2021-07-12 09:57 UTC, TheodorRene commented
> > Legg merke til at Event.EmployeeID er forskjellige fra Participant.EmployeeID
> 
> Kva meiner du med dette? 🤔

De heter det samme, men den ene er av type option int og den andre er av typen int

2021-07-12 09:59 UTC, TheodorRene commented on src/Events/Handlers.fs
> +            let! updatedEvent = Service.updateEvent employeeId (Id id) writeModel
Den er nok litt dum, vi henter allerede hele eventen i servicen, så skal i være nødvending å hente den her. Will fix

2021-07-12 09:59 UTC, TheodorRene commented on src/Participants/Models.fs
> +           }
Jeg synes vi trenger en linter, så jeg slipper å tenke på indentering etc

2021-07-12 10:00 UTC, TheodorRene commented on src/Events/Handlers.fs
> +                            >> Option.withError [UserMessages.couldNotRetrieveUserId] // Result<EmployeeId, UserMessage list>
Jeg synes function composition kan bli litt vanskelig å lese noen ganger. Her funker den ish som en pipe, men Ionide viser ikke typene så jeg gjør det manuelt. Jeg tror det gjør det enklere for folk å forstå hva som skjer her

2021-07-12 11:00 UTC, TheodorRene commented on src/Common/Auth.fs
> +    let employeeIdClaim = "https://api.bekk.no/claims/employeeId"
jeg flytta den lenger opp, lmao

2021-07-12 11:00 UTC, TheodorRene commented on src/Events/UserMessages.fs
> +        $"Kunne ikke hente ut bruker id" |> InternalErrorMessage
fxd

2021-07-12 11:00 UTC, TheodorRene commented on src/Events/Queries.fs
> +            let! event = Models.writeToDomain (Guid.NewGuid()) event (Guid.NewGuid()) false employeeId |> ignoreContext
Kort eksisterer

2021-07-12 11:05 UTC, TheodorRene commented on src/Events/Handlers.fs
> +            let! updatedEvent = Service.updateEvent employeeId (Id id) writeModel
fxd

2021-07-12 13:32 UTC, tskj commented on src/Participants/Models.fs
> +           }
Haha ja! Gjerne se på det om du gidder 😅

2021-07-12 13:54 UTC, tskj requested changes
Smooth 🙌

2021-07-12 13:54 UTC, tskj commented on src/Common/Auth.fs
> +            let! userId = getUserId >> Option.withError ([NotLoggedIn $"Could not retrieve UserId"])
🔪 Unødige parens

2021-07-12 13:54 UTC, tskj commented on src/Events/Handlers.fs
> +                        routef "/localstorage/%i" (fun id ->
Har lyst å førelså at vi bruker eit anna navn på dette endepunktet, det er litt rart at backend assumer / bryr seg om at det lagres i local storage. Feks `/my-stuff/%i` eller `/my-events/%i` eller `/my-events-and-participations/%i`.

2021-07-12 13:54 UTC, tskj commented on src/Events/Handlers.fs
> +            let! newEvent = Service.createEvent createEditUrl employeeId.Unwrap writeModel
Det er rart synes eg at organizerId her skal endre seg for kvar person som redigerer arrangementet (feks admin?), i staden for at den  bare forblir den opprinnelige employeeIden til personen som oppretta arrangementet

2021-07-12 13:54 UTC, tskj commented on src/Participants/Models.fs
> +  }
Kanskje desse ikkje heilt hører heime i `Participants`, men veit ikkje om vi har ein meir passande plass?

2021-07-12 13:54 UTC, tskj commented on src/Participants/Models.fs
> +    let DomainToLocalStorageView events (participations: Participant seq) : ViewModelLocalStorage =
Pascal-case? 🤔

2021-07-13 07:58 UTC, TheodorRene commented on src/Common/Auth.fs
> +            let! userId = getUserId >> Option.withError ([NotLoggedIn $"Could not retrieve UserId"])
fxd

2021-07-13 08:01 UTC, TheodorRene commented on src/Events/Handlers.fs
> +                        routef "/localstorage/%i" (fun id ->
jeg foreslår events-and-participations, unødvending med "my"-prefix

2021-07-13 08:02 UTC, TheodorRene commented on src/Events/Handlers.fs
> +            let! newEvent = Service.createEvent createEditUrl employeeId.Unwrap writeModel
Hmm, vi har jo ikke noen versjonshistorikk. Jeg liker egentlig best at den som opprettet arrangmentet originalt skal stå som organizer. Hvis vi skulle endret hver gang så burde det vært en "LastUpdateById"felt i databasen

2021-07-13 08:03 UTC, TheodorRene commented on src/Participants/Models.fs
> +  }
Ja det er jo på en måte like mye events, som participations. Så trenger gjerne et forslag før jeg evt bytter. Hvis jeg ikke husker feil kan jeg ikke ha det i Event/Models på grunn av dependency-problemer

2021-07-13 08:04 UTC, TheodorRene commented on src/Participants/Models.fs
> +    let DomainToLocalStorageView events (participations: Participant seq) : ViewModelLocalStorage =
fixed

2021-07-13 08:14 UTC, tskj commented on src/Events/Handlers.fs
> +            let! newEvent = Service.createEvent createEditUrl employeeId.Unwrap writeModel
Ja helt enig, men  det ser ut for meg som koden her gjør nettopp det (oppdaterer kvar gang)?

2021-07-13 08:14 UTC, tskj commented on src/Events/Handlers.fs
> +                        routef "/localstorage/%i" (fun id ->
Topp!

2021-07-13 08:30 UTC, merged