Fix create participant development
bekk/bekk-arrangement-svc pull request #56
Opened 2022-03-08 10:04 UTC by Bjorn-Strom

Denne endringen legger til en "enklere" register-participant endepunkt.
Målet med denne PRen er at systemet ikke skal brekke når folk registrerer seg.

Følgende kodeendringer er gjort:
- Lagt til 2 nye filter i en mappe `V2`
     -  `Queries.fs` som har database queries i SQL som bruker Dapper
     -  `Handlers.fs` som har en ny route handler.
- Loggingen er fjernet, skal erstattes med logging biblioteket senere.

2022-03-08 10:58 UTC, toragunstad approved these changes
Bra jobba, Bjørn-Ivar 🐻 🤗

2022-03-08 10:58 UTC, toragunstad commented on src/Events/Models.fs
> +              EndDate = customToDateTime writeModel.StartDate.Date
Her bruker vi `writeModel.StartDate.Date` på `EndDate` :eyes: Er det en grunn til det? 😄

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +    // Eventet har ikke nok ledig plass plass
`plass plass` 🕵️‍♀️

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +            let! body = context.ReadBodyFromRequestAsync()
Hva betyr bruken av utropstegn her? 🤓

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +                                Error "Eventet er ikke åpen for registering"
Bytte fra `åpen` til `åpent`? 🧐

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +                                Error "Eventet tok sted i fortiden"
Jeg liker egentlig ordet arrangement bedre enn event på norsk, men det er bare min preferanse hehe 😄

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +                                        // FIXME: Here we need to fetch all the questions from the database. This is because we have no question ID related to the answers. This does not feel right an
Er det noe som må fikses her? 👀

2022-03-08 10:58 UTC, toragunstad commented on src/V2/Handlers.fs
> +                            // FIXME: we need these domain models as the rest of the system all work with these
Fixme?

2022-03-08 11:01 UTC, Bjorn-Strom commented on src/Events/Models.fs
> +              EndDate = customToDateTime writeModel.StartDate.Date
Du har et øye for detaljer! :D

2022-03-08 11:03 UTC, Bjorn-Strom commented on src/V2/Handlers.fs
> +            let! body = context.ReadBodyFromRequestAsync()
Sååååå, `task {}` er måten man skriver Tasks på i F#.
I C# skriver du at metoden du er i er en task, f.eks
`Task<IEmployee> GetEmployee blablabla`.
Når du ønsker å bruke innholdet i en task, altså `IEmployee` må den awaites.
I C# blir det `var employee = await GetEmployee.....`
I F# skriver man bare `let!` inne i en Task blokk.
Så `let!` er det samme som `var X = await`

2022-03-08 11:04 UTC, Bjorn-Strom commented on src/V2/Handlers.fs
> +                                Error "Eventet er ikke åpen for registering"
Yes!

2022-03-08 11:04 UTC, Bjorn-Strom commented on src/V2/Handlers.fs
> +                                Error "Eventet tok sted i fortiden"
Vi kan godt bruke norsk! :D Sikkert en bedre løsning

2022-03-08 11:05 UTC, Bjorn-Strom commented on src/V2/Handlers.fs
> +                                        // FIXME: Here we need to fetch all the questions from the database. This is because we have no question ID related to the answers. This does not feel right an
På sikt, ja det vil jeg si.
Det er en litt teit måte å gjøre ting på akkurat nå.

2022-03-08 11:05 UTC, Bjorn-Strom commented on src/V2/Handlers.fs
> +                            // FIXME: we need these domain models as the rest of the system all work with these
Yes, bruker fixme da todos lager gule greier i margen i Rider og det var litt distraherende.
Tenkte å lage lapper på dette vi kan snakke om senere

2022-03-10 19:27 UTC, Jonassen requested changes
Jeg vil egentlig ha en diskusjon til på TXhåndteringen nå som vi endte opp med flere databasekall

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Auth.fs
> +                None
Hva er forskjellen på denne og V1? Er det handler-biten?

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Auth.fs
> +                None
Hva er forskjellen på denne og V1? Er det handler-biten?

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                return! convertUserMessagesToHttpError [] next ctx // Default is 500 Internal Server Error
Hvordan er det med bruk av createConnection? Krever den også en close?

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                return! convertUserMessagesToHttpError [] next ctx // Default is 500 Internal Server Error
Hvordan er det med bruk av createConnection? Krever den også en close?

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                Database.rollbackTransaction ctx
Her ruller vi tilbake transaksjon. Men det står ingenting her om transaksjonen allerede finnes, er opprettet, eller commitet. 

Vi burde virkelig samle all transaksjonshåndtering til å være så samlet som mulig.

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                Database.rollbackTransaction ctx
Her ruller vi tilbake transaksjon. Men det står ingenting her om transaksjonen allerede finnes, er opprettet, eller commitet. 

Vi burde virkelig samle all transaksjonshåndtering til å være så samlet som mulig.

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                            return! convertUserMessagesToHttpError [] next ctx
Hva betyr dette? Har ikke denne ingen error?

2022-03-10 19:27 UTC, Jonassen commented on src/Common/Http.fs
> +                            return! convertUserMessagesToHttpError [] next ctx
Hva betyr dette? Har ikke denne ingen error?

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +        CanParticipate
Denne er fin. Veldig god samling av _all_ logikk som bestemmer om man kan bli med på et event.

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +        CanParticipate
Denne er fin. Veldig god samling av _all_ logikk som bestemmer om man kan bli med på et event.

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +            use transaction = dbConnection.BeginTransaction()
Her kjenner jeg at jeg synes det skjer ganske mange ting mellom transaksjonsstart og slutt. 
Det er noe jeg har brent meg på flere ganger før og nå med skjer tidligere igjen. 

Transaksjonens start og slutt (både via commit og rollback) er svært tett koblet sammen og det at de skjer ~75 linjer fra hverandre er litt skummelt.

Det som gjør det enda verre er at det skjer ting inni transaksjonen som kan skje før eller etter.

Noe av det første som skjer her er lesing av request body. Det har ingenting med transaksjonen å gjøre og er data som kan forberedes på forhånd. Mapping til writeModel kan også skje utenom.

I slutten av denne kodeblokken skjer det også noe feilhåndtering som ser ut som at det skrives om til feilmelding til bruker. Dette kan godt gjøres etter at transaksjonen er rullet tilbake.

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +            use transaction = dbConnection.BeginTransaction()
Her kjenner jeg at jeg synes det skjer ganske mange ting mellom transaksjonsstart og slutt. 
Det er noe jeg har brent meg på flere ganger før og nå med skjer tidligere igjen. 

Transaksjonens start og slutt (både via commit og rollback) er svært tett koblet sammen og det at de skjer ~75 linjer fra hverandre er litt skummelt.

Det som gjør det enda verre er at det skjer ting inni transaksjonen som kan skje før eller etter.

Noe av det første som skjer her er lesing av request body. Det har ingenting med transaksjonen å gjøre og er data som kan forberedes på forhånd. Mapping til writeModel kan også skje utenom.

I slutten av denne kodeblokken skjer det også noe feilhåndtering som ser ut som at det skrives om til feilmelding til bruker. Dette kan godt gjøres etter at transaksjonen er rullet tilbake.

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +                                let redirectUrlTemplate =
Bare for å sjekke: Har vi noe kontroll på retries eller lignende hvis denne mailutsendingen feiler?

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Handlers.fs
> +                                let redirectUrlTemplate =
Bare for å sjekke: Har vi noe kontroll på retries eller lignende hvis denne mailutsendingen feiler?

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Queries.fs
> +        OUTPUT INSERTED.*
Nå snakker vi!

2022-03-10 19:27 UTC, Jonassen commented on src/V2/Queries.fs
> +        OUTPUT INSERTED.*
Nå snakker vi!

2022-03-14 13:23 UTC, Bjorn-Strom commented on src/Common/Auth.fs
> +                None
Ja det stemmer. Det er handler biten!

2022-03-15 12:24 UTC, merged